const teamLogoMap = {
'ARI': 'ARI.png',
'ATL': 'ATL.png',
'BAL': 'BAL.png',
'BUF': 'BUF.png',
'CAR': 'CAR.png',
'CHI': 'CHI.png',
'CIN': 'CIN.png',
'CLE': 'CLE.png',
'DAL': 'DAL.png',
'DEN': 'DEN.png',
'DET': 'DET.png',
'GB': 'GB.png',
'HOU': 'HOU.png',
'IND': 'IND.png',
'JAX': 'JAX.png',
'KC': 'KC.png',
'LAC': 'LAC.png',
'LAR': 'LAR.png',
'LAS': 'LAS.png',
'MIA': 'MIA.png',
'MIN': 'MIN.png',
'NE': 'NE.png',
'NO': 'NO.png',
'NYG': 'NYG.png',
'NYJ': 'NYJ.png',
'PHI': 'PHI.png',
'PIT': 'PIT.png',
'SEA': 'SEA.png',
'SF': 'SF.png',
'TB': 'TB.png',
'TEN': 'TEN.png',
'WSH': 'WSH.png',
};

module.exports = teamLogoMap;