const teamLogoMap = {
'ARI': 'ari.png',
'ATL': 'atl.png',
'BAL': 'bal.png',
'BUF': 'buf.png',
'CAR': 'car.png',
'CHI': 'chi.png',
'CIN': 'cin.png',
'CLE': 'cle.png',
'DAL': 'dal.png',
'DEN': 'den.png',
'DET': 'det.png',
'GB': 'gb.png',
'HOU': 'hou.png',
'IND': 'ind.png',
'JAX': 'jax.png',
'KC': 'kc.png',
'LAC': 'lac.png',
'LAR': 'lar.png',
'LAS': 'las.png',
'MIA': 'mia.png',
'MIN': 'min.png',
'NE': 'ne.png',
'NO': 'no.png',
'NYG': 'nyg.png',
'NYJ': 'nyj.png',
'PHI': 'phi.png',
'PIT': 'pit.png',
'SEA': 'sea.png',
'SF': 'sf.png',
'TB': 'tb.png',
'TEN': 'ten.png',
'WSH': 'wsh.png',
};

module.exports = teamLogoMap;